CREATE TABLE movie(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  silent BOOLEAN,
  FOREIGN KEY (item_id) REFERENCES item (id)
);

CREATE TABLE source(
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(100) NOT NULL,
);
