CREATE MOVIE(
  ID SERIAL PRIMARY KEY,
  SOURCE_ID INT,
  LABEL_ID FOREIGN KEY (LABEL_ID) REFERENCES LABELS (ID) ON DELETE SET NULL,
  PUBLISH_DATE DATE,
  ARCHIVED BOOLEAN,
  SILENT BOOLEAN,
);

ALTER TABLE MOVIE CONSTRAINT FK_SOURCE FOREGIN KEY (SOURCE_ID) REFERENCES SOURCE (ID)
